import { OrderItem } from './order-item.model';

export interface Order {
  id?: number; // Auto-generated by DB
  customerName: string;
  orderDate: string; // ISO 8601 date string (e.g., "2024-05-28T10:30:00.000Z")
  totalAmount: number;
  items?: OrderItem[]; // When fetching an order, you might want to include its items
  // status?: OrderStatus; // Optional: e.g., Pending, Completed, Cancelled
}

// Optional: Define order statuses if needed in the future
// export enum OrderStatus {
//   PENDING = 'Pending',
//   COMPLETED = 'Completed',
//   CANCELLED = 'Cancelled',
// }