export interface OrderItem {
  id?: number; // Auto-generated by DB
  orderId: number; // Foreign key linking to the Order
  itemId: number;  // Foreign key linking to the Item
  itemName: string; // Store item name at time of order for historical accuracy
  quantity: number;
  priceAtPurchase: number; // Price of the item at the time of order
}